import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ramlila",
  description: "Generated by ISKCON",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background: "linear-gradient(to right bottom, #241055, #8D1577)"}}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
